version:  "3.9"

services:
    robofriends:
        container_name: robofriends-frontend
        build: ./
        working_dir: /user/src/robotsfriends
        command: npm start
        ports:
            - "3000:3000"
 
 
