version: 2.1
jobs:
  sally:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "He, i'm sally! i love circleci" # run the `echo` command

  dany:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "He, i'm dany! i love circleci" # run the `echo` command

  workflows:
    version: 2.1
    sally_dany:
      jobs:
        - sally
        - dany